-- Create user_preferences table
CREATE TABLE IF NOT EXISTS public.user_preferences (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  user_id     text NOT NULL UNIQUE,
  email       text NOT NULL,
  categories  text[] NOT NULL DEFAULT '{}',
  frequency   text NOT NULL DEFAULT 'daily',
  is_active   boolean NOT NULL DEFAULT true
);

